name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# Do this eventually for uploading tests
# permissions:
#   contents: read
#   checks: write
#   pull-requests: read

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcriterion-dev build-essential

    - name: Run tests
      run: make tests

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/

    # Do later
    # - name: Publish Test Results
    #   if: always()
    #   uses: dorny/test-reporter@v1
    #   with:
    #     name: "Repo Tests"
    #     path: "test-results/*.xml"
    #     reporter: jest-junit
    #     fail-on-error: true

    - name: Compile Binaries
      run: make builds

    - name: Upload binaries on success
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ./bins/

