name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcriterion-dev
    - name: Compile & Run tests 
      run: make test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tests-report
        path: tests-report/
        retention-days: 30
