name: Do Everything

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install test dependencies
      run: |
        sudo apt-get install -y libcriterion-dev

    - name: Run tests
      run: make tests

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/

    - name: Compile Binaries
      run: make builds

    - name: Upload binaries on success
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ./bins/

